name: Main build and Run

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Ubuntu Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: '0'
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake
          ninja --version
          cmake --version
          gcc --version
      - name: Configure
        shell: bash
        run: |
          cmake \
            -S . \
            -B . \
            -D CMAKE_BUILD_TYPE=Release \
            -G "Ninja"
      - name: Build
        shell: bash
        run: cmake --build . --config Release
      - name: Run
        shell: bash
        run: |
          chmod +x tests/test_run.sh
          tests/test_run.sh